import { StyleSheet } from "react-native";
import { UCaldasTheme } from "../../app/constants/Colors";

export const profileStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#f4f6f8" },
    loadingContainer: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
        backgroundColor: UCaldasTheme.azulOscuro,
    },
    loadingText: { color: "#fff", marginTop: 15, fontWeight: "500" },
    content: { padding: 20 },
    headerCard: {
        backgroundColor: "#fff",
        padding: 25,
        borderRadius: 25,
        alignItems: "center",
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        marginTop: 10,
        marginBottom: 10,
    },
    transparentHeader: {
        alignItems: "center",
        paddingVertical: 20,
        marginBottom: 10,
    },
    sectionCard: {
        backgroundColor: "#fff",
        padding: 25,
        borderRadius: 25,
        elevation: 4,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 2 },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        marginTop: 10,
        marginBottom: 15,
    },
    avatarCircle: {
        width: 80,
        height: 80,
        borderRadius: 40,
        backgroundColor: UCaldasTheme.dorado,
        justifyContent: "center",
        alignItems: "center",
    },
    avatarText: { fontSize: 35, color: "#fff", fontWeight: "bold" },
    mainTitle: {
        fontSize: 22,
        fontWeight: "bold",
        marginTop: 15,
        textAlign: "center",
    },
    careerBadge: {
        color: UCaldasTheme.azulOscuro,
        marginTop: 2,
        marginBottom: 5,
        fontWeight: "600",
        opacity: 0.8,
    },
    monitorBadge: {
        backgroundColor: UCaldasTheme.dorado,
        paddingHorizontal: 15,
        paddingVertical: 6,
        borderRadius: 20,
        alignSelf: "flex-start",
        marginBottom: 10,
    },
    monitorText: { color: UCaldasTheme.blanco, fontSize: 12, fontWeight: "bold" },
    sectionLabel: {
        fontSize: 15,
        fontWeight: "bold",
        color: UCaldasTheme.azulOscuro,
        marginTop: 5,
        marginBottom: 15,
    },
    subjectDisplay: {
        backgroundColor: "#f9fafb",
        padding: 15,
        borderRadius: 12,
        marginBottom: 8,
        borderWidth: 1,
        borderColor: "#eee",
    },
    subjectText: { fontWeight: "500", color: "#374151", fontSize: 14 },
    emptyText: { textAlign: "center", color: "#666", marginTop: 10 },
    editButton: {
        backgroundColor: UCaldasTheme.azulOscuro,
        padding: 18,
        borderRadius: 15,
        flexDirection: "row",
        justifyContent: "center",
        alignItems: "center",
        marginTop: 30,
    },
    editButtonText: { color: "#fff", fontWeight: "bold", fontSize: 16 },
    card: {
        backgroundColor: "#fff",
        borderRadius: 12,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: "#ddd",
    },
    rowCard: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        backgroundColor: "#fff",
        padding: 18,
        borderRadius: 15,
        marginBottom: 20,
    },
    label: { fontWeight: "600", color: "#374151" },
    formTitle: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 20,
        color: UCaldasTheme.azulOscuro,
    },
    sectionTitle: {
        color: UCaldasTheme.dorado,
        fontWeight: "bold",
        fontSize: 13,
        marginBottom: 10,
        textTransform: "uppercase",
    },
    subjectItem: {
        backgroundColor: "#fff",
        padding: 16,
        borderRadius: 12,
        marginBottom: 8,
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        borderWidth: 1,
        borderColor: "#eee",
    },
    selected: {
        backgroundColor: UCaldasTheme.azulOscuro,
        borderColor: UCaldasTheme.azulOscuro,
    },
    whiteText: { color: "#fff", fontWeight: "600" },
    blackText: { color: "#374151" },
    saveButton: {
        backgroundColor: UCaldasTheme.dorado,
        padding: 18,
        borderRadius: 15,
        alignItems: "center",
        marginTop: 10,
    },
    saveText: {
        color: UCaldasTheme.azulOscuro,
        fontWeight: "bold",
        fontSize: 16,
    },
    cancelLink: { marginTop: 20, alignItems: "center" },
    cancelText: { color: "#666", fontSize: 14 },
    input: {
        backgroundColor: "#fff",
        borderRadius: 12,
        borderWidth: 1,
        borderColor: "#ddd",
        padding: 15,
        marginBottom: 15,
        color: "#374151",
        fontSize: 15,
    },
    textArea: { height: 100, textAlignVertical: "top" },
    charCount: {
        textAlign: "right",
        color: "#666",
        fontSize: 12,
        marginTop: -10,
        marginBottom: 15,
    },
    infoText: { fontSize: 15, color: "#4b5563", marginTop: 5 },
    infoRow: {
        flexDirection: "row",
        alignItems: "center",
        marginBottom: 12,
    },
    infoValue: {
        marginLeft: 10,
        fontSize: 15,
        color: "#4b5563",
    },
    bioContainer: {
        marginTop: 15,
        padding: 15,
        backgroundColor: "#f9fafb",
        borderRadius: 12,
        width: "100%",
        borderWidth: 1,
        borderColor: "#eee",
    },
    bioTitle: {
        fontWeight: "bold",
        color: UCaldasTheme.azulOscuro,
        marginBottom: 8,
        fontSize: 15,
    },
    bioText: { color: "#4b5563", fontSize: 14, lineHeight: 22 },
});
