import { StyleSheet } from 'react-native';
import { UCaldasTheme } from '../constants/Colors';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#fcfcfc',
    },
    headerNav: {
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        paddingHorizontal: 20,
        paddingTop: 10,
        paddingBottom: 15,
        backgroundColor: '#fcfcfc',
    },
    backCircle: {
        width: 45,
        height: 45,
        borderRadius: 23,
        backgroundColor: '#fff',
        justifyContent: 'center',
        alignItems: 'center',
        elevation: 2,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 1 },
        shadowOpacity: 0.1,
        shadowRadius: 2,
    },
    headerNavTitle: {
        fontSize: 18,
        fontWeight: 'bold',
        color: UCaldasTheme.azulOscuro,
    },
    loadingContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#fff',
    },
    loadingText: {
        marginTop: 12,
        color: '#666',
        fontSize: 16,
    },
    errorContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    errorText: {
        fontSize: 18,
        color: '#666',
        marginTop: 10,
        marginBottom: 20,
    },
    backButton: {
        paddingVertical: 10,
        paddingHorizontal: 20,
        backgroundColor: UCaldasTheme.azulOscuro,
        borderRadius: 8,
    },
    backButtonText: {
        color: '#fff',
        fontWeight: 'bold',
    },
    scrollContent: {
        padding: 20,
        paddingTop: 10,
    },
    mainInfoCard: {
        backgroundColor: '#fff',
        borderRadius: 24,
        padding: 24,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#f0f0f0',
        elevation: 4,
        shadowColor: '#000',
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.05,
        shadowRadius: 10,
    },
    groupHeader: {
        alignItems: 'center',
        marginTop: 10,
    },
    groupName: {
        fontSize: 32,
        fontWeight: '900',
        color: UCaldasTheme.azulOscuro,
        textAlign: 'center',
        marginBottom: 12,
    },
    subjectBox: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#fff9f0',
        paddingVertical: 6,
        paddingHorizontal: 12,
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#ffe8c2',
        marginBottom: 16,
        gap: 8,
    },
    subjectName: {
        fontSize: 16,
        color: UCaldasTheme.dorado,
        fontWeight: '700',
    },
    badgeWrapper: {
        marginTop: 5,
    },
    adminBadge: {
        backgroundColor: UCaldasTheme.azulOscuro,
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 8,
        paddingHorizontal: 16,
        borderRadius: 25,
        gap: 8,
    },
    adminBadgeText: {
        color: '#fff',
        fontSize: 13,
        fontWeight: '900',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    sectionCard: {
        backgroundColor: '#fff',
        borderRadius: 20,
        padding: 20,
        marginBottom: 20,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    sectionHeader: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 15,
        gap: 10,
        borderBottomWidth: 1,
        borderBottomColor: '#f5f5f5',
        paddingBottom: 10,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: '800',
        color: '#444',
        textTransform: 'uppercase',
        letterSpacing: 0.8,
    },
    description: {
        fontSize: 16,
        color: '#555',
        lineHeight: 24,
    },
    membersList: {
        gap: 12,
    },
    memberItem: {
        flexDirection: 'row',
        alignItems: 'center',
        padding: 12,
        backgroundColor: '#fff',
        borderRadius: 15,
        borderWidth: 1,
        borderColor: '#f0f0f0',
    },
    memberAvatar: {
        width: 44,
        height: 44,
        borderRadius: 22,
        backgroundColor: '#f0f2f5',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    avatarText: {
        fontSize: 20,
        fontWeight: '800',
        color: UCaldasTheme.azulOscuro,
    },
    memberInfo: {
        flex: 1,
    },
    memberName: {
        fontSize: 16,
        fontWeight: '700',
        color: '#333',
    },
    memberRole: {
        fontSize: 13,
        color: '#888',
        marginTop: 2,
    },
    starCircle: {
        width: 24,
        height: 24,
        borderRadius: 12,
        backgroundColor: UCaldasTheme.dorado,
        justifyContent: 'center',
        alignItems: 'center',
    },
    footerContainer: {
        padding: 16,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderColor: '#eee',
        shadowColor: '#000',
        shadowOffset: { width: 0, height: -3 },
        shadowOpacity: 0.05,
        shadowRadius: 5,
        elevation: 10,
    },
    requestButton: {
        flexDirection: 'row',
        backgroundColor: UCaldasTheme.azulOscuro,
        paddingVertical: 14,
        borderRadius: 12,
        justifyContent: 'center',
        alignItems: 'center',
    },
    requestButtonDisabled: {
        backgroundColor: '#999',
    },
    requestButtonText: {
        color: '#fff',
        fontSize: 16,
        fontWeight: 'bold',
    },
});
