import { StyleSheet, Platform } from 'react-native';
import { UCaldasTheme } from '@/app/constants/Colors';

export const styles = StyleSheet.create({
    overlay: {
        flex: 1,
        backgroundColor: 'rgba(0,0,0,0.6)',
        justifyContent: 'flex-end',
    },
    modalContainer: {
        backgroundColor: '#fff',
        borderTopLeftRadius: 28,
        borderTopRightRadius: 28,
        padding: 24,
        maxHeight: '90%',
        shadowColor: "#000",
        shadowOffset: { width: 0, height: -4 },
        shadowOpacity: 0.1,
        shadowRadius: 10,
        elevation: 20,
    },
    header: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 20,
    },
    closeButton: {
        padding: 4,
        backgroundColor: '#f0f0f0',
        borderRadius: 20,
    },
    title: {
        fontSize: 24,
        fontWeight: '800',
        color: UCaldasTheme.azulOscuro,
    },
    subtitle: {
        fontSize: 14,
        color: '#666',
        marginTop: 2,
    },
    form: {
        marginBottom: 10,
    },
    label: {
        fontSize: 14,
        fontWeight: '700',
        color: UCaldasTheme.azulOscuro,
        marginBottom: 8,
        marginTop: 16,
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    input: {
        borderWidth: 1.5,
        borderColor: '#eee',
        borderRadius: 12,
        padding: 14,
        fontSize: 16,
        backgroundColor: '#fcfcfc',
        color: '#333',
    },
    textArea: {
        height: 90,
        textAlignVertical: 'top',
    },
    selectorWrapper: {
        backgroundColor: '#fafafa',
        borderRadius: 12,
        borderWidth: 1.5,
        borderColor: '#eee',
        overflow: 'hidden',
        marginTop: 4,
    },
    chipsContainer: {
        flexDirection: "row",
        flexWrap: "wrap",
        gap: 8,
        padding: 16,
        backgroundColor: '#fff',
        borderTopWidth: 1,
        borderTopColor: '#f0f0f0',
    },
    chip: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 10,
        paddingHorizontal: 16,
        backgroundColor: "#f0f0f0",
        borderRadius: 25,
        borderWidth: 1,
        borderColor: 'transparent',
    },
    chipActive: {
        backgroundColor: UCaldasTheme.azulOscuro,
        borderColor: UCaldasTheme.azulOscuro,
    },
    chipText: {
        fontSize: 14,
        color: "#444",
        fontWeight: '600',
    },
    chipTextActive: {
        color: "#ffffff",
        fontWeight: "700",
    },
    emptyText: {
        width: '100%',
        padding: 20,
        color: '#999',
        fontStyle: 'italic',
        textAlign: 'center',
    },
    footer: {
        marginTop: 20,
        paddingBottom: Platform.OS === 'ios' ? 20 : 0,
    },
    submitButton: {
        backgroundColor: UCaldasTheme.azulOscuro,
        flexDirection: 'row',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 18,
        borderRadius: 16,
        shadowColor: UCaldasTheme.azulOscuro,
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.3,
        shadowRadius: 8,
        elevation: 8,
    },
    disabledButton: {
        backgroundColor: '#ccc',
        shadowOpacity: 0,
        elevation: 0,
    },
    submitButtonText: {
        color: '#fff',
        fontSize: 17,
        fontWeight: '800',
    },
});
