import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        flexDirection: 'row',
        backgroundColor: '#f4f7fc',
    },
    sidebar: {
        width: 260,
        backgroundColor: '#ffffff',
        paddingVertical: 15,
        borderRightWidth: 1,
        borderRightColor: '#e5eeff',
    },
    backButton: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 24,
        marginBottom: 30,
    },
    backText: {
        color: '#708ab5',
        marginLeft: 8,
        fontSize: 14,
        fontWeight: '600',
    },
    groupInfoSidebar: {
        paddingHorizontal: 24,
        marginBottom: 30,
    },
    sidebarGroupName: {
        color: '#002147',
        fontSize: 18,
        fontWeight: '700',
        marginBottom: 4,
    },
    sidebarSubject: {
        color: '#708ab5',
        fontSize: 11,
        fontWeight: '700',
        textTransform: 'uppercase',
        letterSpacing: 0.5,
    },
    menu: {
        flex: 1,
    },
    menuSectionTitle: {
        color: '#a0b3c6',
        fontSize: 10,
        fontWeight: '700',
        paddingHorizontal: 24,
        marginBottom: 10,
        letterSpacing: 1,
    },
    menuItem: {
        flexDirection: 'row',
        alignItems: 'center',
        paddingVertical: 12,
        paddingHorizontal: 24,
        borderLeftWidth: 3,
        borderLeftColor: 'transparent',
    },
    menuItemActive: {
        backgroundColor: '#f8f9ff',
        borderLeftColor: '#B8860B',
    },
    menuText: {
        color: '#44474e',
        marginLeft: 12,
        fontSize: 14,
        fontWeight: '500',
        flex: 1,
    },
    menuTextActive: {
        color: '#002147',
        fontWeight: '700',
    },
    menuBadge: {
        backgroundColor: '#d93025',
        borderRadius: 10,
        paddingHorizontal: 6,
        paddingVertical: 2,
    },
    menuBadgeText: {
        color: '#fff',
        fontSize: 10,
        fontWeight: '700',
    },
    mainContentScrollView: {
        flex: 1,
    },
    mainContent: {
        padding: 40,
        minHeight: '100%',
    },
    header: {
        marginBottom: 30,
    },
    breadcrumb: {
        color: '#708ab5',
        fontSize: 13,
        marginBottom: 10,
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    titleRow: {
        flexDirection: 'row',
        alignItems: 'center',
        gap: 10,
        marginBottom: 6,
    },
    pageTitle: {
        fontSize: 28,
        fontWeight: '700',
        color: '#002147',
    },
    statusBadge: {
        backgroundColor: '#fdf6e3',
        borderWidth: 1,
        borderColor: '#f4e0b3',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 4,
    },
    statusText: {
        color: '#b8860b',
        fontSize: 10,
        fontWeight: '700',
    },
    pageSubtitle: {
        fontSize: 15,
        color: '#708ab5',
    },
    primaryButton: {
        backgroundColor: '#002147',
        flexDirection: 'row',
        alignItems: 'center',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 6,
    },
    primaryButtonText: {
        color: '#ffffff',
        fontWeight: '600',
        fontSize: 14,
    },
    contentLayout: {
        flexDirection: 'row',
        gap: 24,
        alignItems: 'flex-start',
    },
    leftColumn: {
        flex: 1,
    },
    rightColumn: {
        width: 320,
    },
    statsRow: {
        flexDirection: 'row',
        gap: 16,
        marginBottom: 24,
    },
    statCard: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 20,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'space-between',
        borderWidth: 1,
        borderColor: '#e5eeff',
        shadowColor: '#000',
        shadowOpacity: 0.02,
        shadowRadius: 10,
        elevation: 1,
    },
    statTitle: {
        fontSize: 13,
        color: '#708ab5',
        fontWeight: '600',
        marginBottom: 6,
    },
    statValue: {
        fontSize: 28,
        fontWeight: '700',
        color: '#002147',
        marginBottom: 4,
    },
    statSub: {
        fontSize: 12,
        fontWeight: '600',
    },
    statIconWrapper: {
        width: 48,
        height: 48,
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
    },
    tableCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e5eeff',
        shadowColor: '#000',
        shadowOpacity: 0.02,
        shadowRadius: 10,
        elevation: 1,
    },
    tableHeaderSection: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f4ff',
    },
    tableTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#002147',
    },
    searchBox: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e5eeff',
        paddingHorizontal: 12,
        paddingVertical: 8,
        borderRadius: 6,
        width: 200,
    },
    searchText: {
        color: '#708ab5',
        marginLeft: 8,
        fontSize: 13,
    },
    tableColHeader: {
        flexDirection: 'row',
        backgroundColor: '#002147',
        paddingHorizontal: 20,
        paddingVertical: 12,
    },
    colHeaderText: {
        color: '#ffffff',
        fontSize: 11,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    tableRow: {
        flexDirection: 'row',
        paddingHorizontal: 20,
        paddingVertical: 16,
        borderBottomWidth: 1,
        borderBottomColor: '#f0f4ff',
    },
    rowAvatar: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#e5eeff',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 12,
    },
    rowAvatarText: {
        color: '#002147',
        fontWeight: '700',
        fontSize: 12,
    },
    rowName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#002147',
    },
    roleBadgeAdmin: {
        backgroundColor: '#002147',
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    roleTextAdmin: {
        color: '#ffffff',
        fontSize: 11,
        fontWeight: '600',
    },
    roleBadgeStudent: {
        backgroundColor: '#f0f4ff',
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    roleTextStudent: {
        color: '#708ab5',
        fontSize: 11,
        fontWeight: '600',
    },
    statusBadgeActive: {
        backgroundColor: '#e6f4ea',
        alignSelf: 'flex-start',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 12,
    },
    statusTextActive: {
        color: '#1e8e3e',
        fontSize: 11,
        fontWeight: '600',
    },
    tableFooter: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        padding: 20,
        backgroundColor: '#fafbff',
        borderBottomLeftRadius: 12,
        borderBottomRightRadius: 12,
    },
    extraChatBtn: {
        backgroundColor: '#002147',
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        margin: 20,
        paddingVertical: 12,
        borderRadius: 8,
    },
    extraChatBtnText: {
        color: '#ffffff',
        fontWeight: '700',
        fontSize: 14,
    },
    footerText: {
        fontSize: 13,
        color: '#708ab5',
    },
    pageBtn: {
        borderWidth: 1,
        borderColor: '#e5eeff',
        paddingHorizontal: 12,
        paddingVertical: 6,
        borderRadius: 4,
        backgroundColor: '#ffffff',
    },
    pageBtnText: {
        fontSize: 13,
        color: '#708ab5',
        fontWeight: '500',
    },
    rightCard: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        padding: 24,
        marginBottom: 24,
        borderWidth: 1,
        borderColor: '#e5eeff',
    },
    rightCardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 20,
    },
    rightCardTitle: {
        fontSize: 16,
        fontWeight: '700',
        color: '#002147',
    },
    badge: {
        backgroundColor: '#ffebeb',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    badgeText: {
        color: '#d93025',
        fontSize: 12,
        fontWeight: '700',
    },
    requestItem: {
        marginBottom: 16,
        borderWidth: 1,
        borderColor: '#f0f4ff',
        borderRadius: 8,
        padding: 12,
    },
    requestUser: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 12,
    },
    avatarCP: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#002147',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    avatarLV: {
        width: 32,
        height: 32,
        borderRadius: 16,
        backgroundColor: '#c0ccda',
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 10,
    },
    avatarText: {
        color: '#ffffff',
        fontSize: 12,
        fontWeight: '700',
    },
    requestName: {
        fontSize: 14,
        fontWeight: '600',
        color: '#002147',
    },
    requestActions: {
        flexDirection: 'row',
        gap: 8,
    },
    btnAccept: {
        flex: 1,
        backgroundColor: '#002147',
        paddingVertical: 8,
        borderRadius: 6,
        alignItems: 'center',
    },
    btnAcceptText: {
        color: '#ffffff',
        fontSize: 12,
        fontWeight: '600',
    },
    btnReject: {
        flex: 1,
        backgroundColor: '#ffffff',
        borderWidth: 1,
        borderColor: '#e5eeff',
        paddingVertical: 8,
        borderRadius: 6,
        alignItems: 'center',
    },
    btnRejectText: {
        color: '#708ab5',
        fontSize: 12,
        fontWeight: '600',
    },
    viewAllBtn: {
        alignItems: 'center',
        marginTop: 8,
    },
    viewAllText: {
        color: '#B8860B',
        fontSize: 13,
        fontWeight: '600',
    },
    abandonCard: {
        backgroundColor: '#fffcfc',
        borderRadius: 12,
        padding: 24,
        borderWidth: 1,
        borderColor: '#ffebeb',
        shadowColor: '#d93025',
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    abandonTitle: {
        color: '#d93025',
        fontSize: 16,
        fontWeight: '700',
        marginBottom: 6,
    },
    abandonSub: {
        color: '#708ab5',
        fontSize: 13,
        lineHeight: 20,
    },
    abandonBtn: {
        backgroundColor: '#d93025',
        paddingVertical: 12,
        borderRadius: 6,
        alignItems: 'center',
        marginTop: 5,
    },
    abandonBtnText: {
        color: '#ffffff',
        fontSize: 14,
        fontWeight: '700',
    },
    floatingChatBtn: {
        position: 'absolute',
        bottom: 40,
        right: 40,
        width: 60,
        height: 60,
        backgroundColor: '#B8860B',
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.2,
        shadowRadius: 10,
        elevation: 5,
    }
});
