import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: '#f8f9ff', // Fondo principal según diseño
    },
    scrollContent: {
        padding: 40,
        maxWidth: 1400,
        alignSelf: 'center',
        width: '100%',
    },
    breadcrumb: {
        fontSize: 12,
        color: '#002147',
        marginBottom: 10,
        fontFamily: 'Inter',
    },
    headerRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: 40,
    },
    pageTitle: {
        fontSize: 32,
        fontWeight: '700',
        color: '#002147',
        fontFamily: 'Manrope',
        marginBottom: 8,
    },
    pageSubtitle: {
        fontSize: 16,
        color: '#44474e',
        fontFamily: 'Inter',
    },
    primaryButton: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#002147',
        paddingHorizontal: 20,
        paddingVertical: 12,
        borderRadius: 8,
    },
    primaryButtonText: {
        color: '#ffffff',
        fontWeight: '600',
        fontSize: 14,
    },
    tabsContainer: {
        flexDirection: 'row',
        borderBottomWidth: 1,
        borderBottomColor: '#dce9ff',
        marginBottom: 30,
    },
    tab: {
        paddingVertical: 12,
        paddingHorizontal: 20,
        borderBottomWidth: 2,
        borderBottomColor: 'transparent',
    },
    activeTab: {
        borderBottomColor: '#B8860B', // Accent Gold
    },
    tabText: {
        fontSize: 16,
        color: '#708ab5',
        fontWeight: '500',
    },
    activeTabText: {
        color: '#002147',
        fontWeight: '700',
    },
    statsRow: {
        flexDirection: 'row',
        gap: 20,
        marginBottom: 40,
    },
    statCard: {
        flex: 1,
        backgroundColor: '#ffffff',
        padding: 20,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#e5eeff',
        borderLeftWidth: 4,
        flexDirection: 'row',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.03,
        shadowRadius: 10,
        elevation: 2,
    },
    statIconWrapper: {
        width: 48,
        height: 48,
        backgroundColor: '#f0f4ff',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        marginRight: 16,
    },
    statTitle: {
        fontSize: 10,
        fontWeight: '700',
        color: '#708ab5',
        marginBottom: 4,
        letterSpacing: 0.5,
    },
    statValue: {
        fontSize: 24,
        fontWeight: '700',
        color: '#002147',
    },
    gridContainer: {
        flexDirection: 'row',
        flexWrap: 'wrap',
        marginHorizontal: -10,
    },
    gridItem: {
        width: '33.33%', // 3 columnas
        padding: 10,
        minWidth: 320,
    },
    // Estilos de las tarjetas de grupo
    cardContainer: {
        backgroundColor: '#ffffff',
        borderRadius: 12,
        borderWidth: 1,
        borderColor: '#e5eeff',
        overflow: 'hidden',
        position: 'relative',
        shadowColor: '#000',
        shadowOpacity: 0.04,
        shadowRadius: 15,
        elevation: 3,
        height: '100%',
    },
    cardBanner: {
        height: 80,
        width: '100%',
        alignItems: 'flex-end',
        padding: 15,
    },
    roleBadge: {
        backgroundColor: 'rgba(255,255,255,0.2)',
        paddingHorizontal: 10,
        paddingVertical: 4,
        borderRadius: 4,
    },
    roleText: {
        color: '#ffffff',
        fontSize: 10,
        fontWeight: '700',
        letterSpacing: 0.5,
    },
    cardIconContainer: {
        position: 'absolute',
        top: 60,
        left: 20,
        width: 40,
        height: 40,
        backgroundColor: '#ffffff',
        borderRadius: 8,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#000',
        shadowOpacity: 0.1,
        shadowRadius: 5,
        elevation: 4,
    },
    cardContent: {
        padding: 20,
        paddingTop: 30, // Para dar espacio al ícono flotante
        flex: 1,
    },
    cardHeader: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'flex-start',
        marginBottom: 10,
    },
    cardTitle: {
        fontSize: 20,
        fontWeight: '700',
        color: '#002147',
        fontFamily: 'Manrope',
        flex: 1,
        marginRight: 10,
    },
    statusBadge: {
        backgroundColor: '#e6f4ea',
        paddingHorizontal: 8,
        paddingVertical: 4,
        borderRadius: 12,
    },
    statusText: {
        color: '#1e8e3e',
        fontSize: 10,
        fontWeight: '700',
    },
    cardDescription: {
        fontSize: 14,
        color: '#44474e',
        lineHeight: 20,
        marginBottom: 20,
        flex: 1,
    },
    membersRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderTopWidth: 1,
        borderTopColor: '#f0f4ff',
        paddingTop: 15,
    },
    avatarsContainer: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 28,
        height: 28,
        borderRadius: 14,
        borderWidth: 2,
        borderColor: '#ffffff',
    },
    avatarMore: {
        width: 28,
        height: 28,
        borderRadius: 14,
        backgroundColor: '#e5eeff',
        borderWidth: 2,
        borderColor: '#ffffff',
        marginLeft: -10,
        justifyContent: 'center',
        alignItems: 'center',
    },
    avatarMoreText: {
        fontSize: 10,
        color: '#002147',
        fontWeight: '700',
    },
    membersCount: {
        flexDirection: 'row',
        alignItems: 'center',
    },
    membersText: {
        fontSize: 12,
        color: '#44474e',
        fontWeight: '500',
    },
    cardActions: {
        flexDirection: 'row',
        padding: 20,
        paddingTop: 0,
        alignItems: 'center',
    },
    manageButton: {
        flex: 1,
        borderWidth: 1,
        borderColor: '#002147',
        borderRadius: 8,
        paddingVertical: 10,
        alignItems: 'center',
        marginRight: 10,
    },
    manageButtonText: {
        color: '#002147',
        fontWeight: '600',
        fontSize: 14,
    },
    optionsButton: {
        padding: 10,
    },
    // Estilos de tarjeta de crear grupo
    createCardContainer: {
        backgroundColor: 'transparent',
        borderRadius: 12,
        borderWidth: 2,
        borderColor: '#dce9ff',
        borderStyle: 'dashed',
        height: '100%',
        minHeight: 280,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 30,
    },
    createIconWrapper: {
        width: 60,
        height: 60,
        backgroundColor: '#ffffff',
        borderRadius: 30,
        justifyContent: 'center',
        alignItems: 'center',
        marginBottom: 20,
        shadowColor: '#000',
        shadowOpacity: 0.05,
        shadowRadius: 10,
        elevation: 2,
    },
    createCardTitle: {
        fontSize: 18,
        fontWeight: '700',
        color: '#002147',
        marginBottom: 10,
    },
    createCardSub: {
        fontSize: 14,
        color: '#708ab5',
        textAlign: 'center',
        lineHeight: 20,
    },
    // Paginación
    paginationRow: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginTop: 40,
        borderTopWidth: 1,
        borderTopColor: '#dce9ff',
        paddingTop: 20,
    },
    paginationText: {
        fontSize: 14,
        color: '#708ab5',
    },
    paginationControls: {
        flexDirection: 'row',
        gap: 5,
    },
    pageButton: {
        width: 36,
        height: 36,
        borderRadius: 4,
        borderWidth: 1,
        borderColor: '#dce9ff',
        justifyContent: 'center',
        alignItems: 'center',
        backgroundColor: '#ffffff',
    },
    pageButtonActive: {
        backgroundColor: '#002147',
        borderColor: '#002147',
    },
    pageButtonText: {
        color: '#002147',
        fontWeight: '600',
    },
    pageButtonActiveText: {
        color: '#ffffff',
        fontWeight: '600',
    },
});
