import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
  overlay: {
    ...StyleSheet.absoluteFillObject,
    backgroundColor: 'rgba(0,0,0,0.55)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  modal: {
    width: '100%',
    maxWidth: 480,
    backgroundColor: '#ffffff',
    borderRadius: 14,
    padding: 24,
    shadowColor: '#000',
    shadowOpacity: 0.15,
    shadowRadius: 20,
    elevation: 12,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'flex-start',
    marginBottom: 8,
  },
  title: {
    fontSize: 18,
    fontWeight: '700',
    color: '#002147',
    flex: 1,
  },
  subtitle: {
    fontSize: 13,
    color: '#708ab5',
    marginBottom: 16,
  },
  closeBtn: {
    padding: 4,
  },
  label: {
    fontSize: 13,
    fontWeight: '700',
    color: '#002147',
    marginBottom: 10,
    marginTop: 4,
  },
  list: {
    maxHeight: 240,
    borderWidth: 1,
    borderColor: '#e5eeff',
    borderRadius: 8,
    marginBottom: 16,
  },
  memberRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 12,
    paddingHorizontal: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#f0f4ff',
  },
  memberRowSelected: {
    backgroundColor: '#f8f9ff',
  },
  memberRowLast: {
    borderBottomWidth: 0,
  },
  radio: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: '#c0ccda',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
  },
  radioSelected: {
    borderColor: '#002147',
  },
  radioInner: {
    width: 10,
    height: 10,
    borderRadius: 5,
    backgroundColor: '#002147',
  },
  memberAvatar: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: '#e5eeff',
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 10,
  },
  memberAvatarText: {
    color: '#002147',
    fontWeight: '700',
    fontSize: 12,
  },
  memberName: {
    fontSize: 14,
    fontWeight: '600',
    color: '#002147',
    flex: 1,
  },
  emptyText: {
    color: '#708ab5',
    textAlign: 'center',
    padding: 20,
    fontStyle: 'italic',
  },
  warningBanner: {
    backgroundColor: '#fffaeb',
    borderWidth: 1,
    borderColor: '#fde68a',
    borderRadius: 8,
    padding: 12,
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 16,
  },
  warningText: {
    color: '#92400e',
    fontSize: 13,
    flex: 1,
    marginLeft: 8,
    lineHeight: 18,
  },
  actions: {
    flexDirection: 'row',
    justifyContent: 'flex-end',
    gap: 10,
    marginTop: 4,
  },
  btnSecondary: {
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 6,
    borderWidth: 1,
    borderColor: '#e5eeff',
    backgroundColor: '#ffffff',
  },
  btnSecondaryText: {
    color: '#708ab5',
    fontWeight: '600',
    fontSize: 14,
  },
  btnPrimary: {
    paddingVertical: 10,
    paddingHorizontal: 18,
    borderRadius: 6,
    backgroundColor: '#002147',
  },
  btnPrimaryDisabled: {
    backgroundColor: '#c0ccda',
  },
  btnPrimaryText: {
    color: '#ffffff',
    fontWeight: '700',
    fontSize: 14,
  },
});
